import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Michael & Eric's Mission Trip",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body>
        <div className='app-container'>{children}</div>
      </body>
    </html>
  );
}
